"""
Query Executor - Safely executes pandas code generated by the LLM.
"""

import pandas as pd
import numpy as np


def execute_pandas_query(df: pd.DataFrame, pandas_code: str) -> pd.DataFrame:
    """
    Execute LLM-generated pandas code in a restricted environment.
    The code must produce a variable called `result_df`.
    """
    # Restricted globals - only pandas and numpy operations allowed
    safe_globals = {
        "__builtins__": {
            "len": len,
            "range": range,
            "int": int,
            "float": float,
            "str": str,
            "list": list,
            "dict": dict,
            "tuple": tuple,
            "bool": bool,
            "abs": abs,
            "round": round,
            "min": min,
            "max": max,
            "sum": sum,
            "sorted": sorted,
            "enumerate": enumerate,
            "zip": zip,
            "map": map,
            "filter": filter,
            "True": True,
            "False": False,
            "None": None,
        },
        "pd": pd,
        "np": np,
        "df": df.copy(),  # Work on a copy to protect original data
    }

    local_vars = {}

    try:
        exec(pandas_code, safe_globals, local_vars)
    except Exception as e:
        raise RuntimeError(f"Error executing pandas code: {str(e)}\nCode: {pandas_code}")

    if "result_df" not in local_vars:
        raise RuntimeError(
            "The generated code did not produce a 'result_df' variable. "
            "This is likely an LLM output issue."
        )

    result = local_vars["result_df"]

    # Convert Series to DataFrame
    if isinstance(result, pd.Series):
        result = result.reset_index()
        result.columns = [result.columns[0], "Value"] if len(result.columns) == 2 else result.columns

    if not isinstance(result, pd.DataFrame):
        raise RuntimeError(
            f"result_df must be a DataFrame, got {type(result).__name__}"
        )

    return result


def dataframe_to_chart_data(df: pd.DataFrame, x_column: str, y_columns: list) -> list:
    """
    Convert a DataFrame to a list of dicts suitable for Recharts.
    """
    # Validate columns exist
    available_cols = list(df.columns)

    if x_column not in available_cols:
        # Try case-insensitive match
        for col in available_cols:
            if col.lower() == x_column.lower():
                x_column = col
                break
        else:
            # Use first column as fallback
            x_column = available_cols[0]

    valid_y_columns = []
    for yc in y_columns:
        if yc in available_cols:
            valid_y_columns.append(yc)
        else:
            # Try case-insensitive match
            for col in available_cols:
                if col.lower() == yc.lower():
                    valid_y_columns.append(col)
                    break

    if not valid_y_columns:
        # Use all numeric columns except x_column
        valid_y_columns = [
            col for col in available_cols
            if col != x_column and df[col].dtype in ['int64', 'float64', 'int32', 'float32']
        ]

    if not valid_y_columns:
        valid_y_columns = [col for col in available_cols if col != x_column][:1]

    # Build the chart data list
    chart_data = []
    for _, row in df.iterrows():
        entry = {"name": str(row[x_column])}
        for yc in valid_y_columns:
            val = row[yc]
            if pd.isna(val):
                entry[yc] = 0
            elif isinstance(val, (np.integer,)):
                entry[yc] = int(val)
            elif isinstance(val, (np.floating,)):
                entry[yc] = round(float(val), 2)
            else:
                try:
                    entry[yc] = round(float(val), 2)
                except (ValueError, TypeError):
                    entry[yc] = str(val)
        chart_data.append(entry)

    return chart_data, valid_y_columns
